import type { Metadata } from 'next'

import { TheFooter } from '@/shared/ui/TheFooter'
import { TheHeader } from '@/shared/ui/TheHeader'

import { AuthProvider } from './_providers/AuthProvider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <TheHeader />
          <main className='container'>{children}</main>
          <TheFooter />
        </AuthProvider>
      </body>
    </html>
  )
}
