import type { Metadata } from 'next'

import { TheFooter } from '@/app/_components/TheFooter'
import { TheHeader } from '@/app/_components/TheHeader'

import './globals.css'
import { AuthProvider } from './_providers/AuthProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <TheHeader />
          <main className='container'>{children}</main>
          <TheFooter />
        </AuthProvider>
      </body>
    </html>
  )
}
